version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install curl libstdc++6 git wget python-is-python3 gcc clang python3-pip nano && pip3 install telegram-send
           git config --global user.name "MumetNgoding"
           git config --global user.email "nugroho31.com@gmail.com"
           git clone https://github.com/MumetNgoding/BrynKernel-AOSP --depth 1 Q
           cd Q
           chmod a+x gettools.sh
           ./gettools.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
